import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "../../provider";  // Adjust if the path is incorrect
import Header from '../../Components/Header';  // Adjust if the path is incorrect
import MenuDrawer from "@/Components/MenuDrawer";  // Adjust if the path is incorrect
import StoreProvider from "../../Utils/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className} style={{ backgroundColor: '#F0FFF4' }}> {/* Replace with desired color */}
                <StoreProvider>
                    <Providers>
                        <Header />
                        <MenuDrawer />
                        <main>{children}</main>
                    </Providers>
                </StoreProvider>
            </body>
        </html>
    );
}
